### ISSUE TITLE
Well done!

### ISSUE THREAD

**Issue by mjsolidarios** [mgsc924/dart-midterm-output#1]
This was a well-written dart code Mike! I was wondering what was the emoji you used for the stone, so I Googled it - I thought it was a clothes iron :laughing: 

By the way, you can further improve your work by catching invalid inputs from the user.

**Comment by mgsc924** [comment]
Daw muna lng bi abi Sir ang available nga emoji for rock daan daw iron gid mn HAHAHHA

Sige Sir, noted. Thank you gid 😂

**Comment by mjsolidarios** [comment]
Awesome! Submit nyo lang inyo outputs anytime ah. Would like to do code reviews on them.
